### ISSUE TITLE
Typo in proton-ge-custom-meta ebuild: "game-util/steam-meta"  should be "games-util/steam-meta"

### ISSUE THREAD

**Issue by HealerLFG** [CHN-beta/touchfish-os#1]
emerging the proton-ge-custom-meta ebuild from the overlay results in portage exiting with error:
``emerge: there are no ebuilds to satisfy "game-util/steam-meta".
(dependency required by "app-emulation/proton-ge-custom-meta-1::touchfish-os" [ebuild])
(dependency required by "proton-ge-custom-meta"``

**Comment by CHN-beta** [comment]
You are right, thx.
